SELECT TOP (1000) [id]
      ,[source_unique_id]
      ,[crawl_timestamp]
      ,[product_url]
      ,[product_name]
      ,[description]
      ,[list_price]
      ,[sale_price]
      ,[brand]
      ,[item_number]
      ,[gtin]
      ,[package_size]
      ,[category]
      ,[postal_code]
      ,[available]
      ,[embedding]
  FROM [ProductDB].[dbo].[walmart_ecommerce_product_details]